//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freshivoje.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Freshivoje.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string dashInput {
            get {
                return ResourceManager.GetString("dashInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOLIMO POPUNITE SVA POLJA!.
        /// </summary>
        internal static string emptyInputErrorMsg {
            get {
                return ResourceManager.GetString("emptyInputErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOŠLO JE DO GREŠKE. 
        ///MOLIMO POKUŠAJTE PONOVO!.
        /// </summary>
        internal static string errorMsg {
            get {
                return ResourceManager.GetString("errorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEPRAVILAN BANKOVNI RAČUN!
        ///BANKOVNI RAČUN MORA IMATI 13 CIFARA!.
        /// </summary>
        internal static string invalidBankAccountMsg {
            get {
                return ResourceManager.GetString("invalidBankAccountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEPRAVILAN BROJ POLJOPRIVREDNOG GAZDINSTVA!
        ///BROJ POLJOPRIVREDNOG GAZDINSTVA MORA IMATI 12 CIFARA..
        /// </summary>
        internal static string invalidBPGMsg {
            get {
                return ResourceManager.GetString("invalidBPGMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEPRAVILAN JMBG!
        ///JMBG MORA IMATI 13 CIFARA!.
        /// </summary>
        internal static string invalidJMBGMsg {
            get {
                return ResourceManager.GetString("invalidJMBGMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEPRAVILNO KORISNIČKO IME ILI LOZINKA!.
        /// </summary>
        internal static string invalidUsernamePassword {
            get {
                return ResourceManager.GetString("invalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEPRAVILAN POŠTANSKI BROJ!
        ///POŠTANSKI BROJ MORA IMA 5 CIFARA!.
        /// </summary>
        internal static string invalidZipCodeMsg {
            get {
                return ResourceManager.GetString("invalidZipCodeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left_arrow {
            get {
                object obj = ResourceManager.GetObject("left arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minimize {
            get {
                object obj = ResourceManager.GetObject("minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x {
            get {
                object obj = ResourceManager.GetObject("x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
